name: snayp-pages

on:
  push:
    branches:
    - maшт

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: snayp/snayp.github.io
        DEPLOY_BRANCH: gh-pages
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
